services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: delivery-frontend:latest
    container_name: delivery-frontend
    restart: always
    ports:
      - "6000:80"